run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec
    - gocognit
    - gocyclo

linters-settings:
  gocognit:
    min-complexity: 30
  gocyclo:
    min-complexity: 30
  lll:
    line-length: 120

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
