blank_issues_enabled: false
contact_links:
  - name: 🔒 Security Vulnerability (Private)
    url: https://github.com/wallix/terraform-provider-wallix-bastion/security/advisories/new
    about: Report security vulnerabilities privately
  - name: 📚 Wallix Bastion Documentation
    url: https://docs.wallix.com/
    about: Official Wallix Bastion documentation
  - name: 🏗️ Terraform Provider Development
    url: https://developer.hashicorp.com/terraform/plugin
    about: Terraform Provider development documentation
  - name: 💬 Community Discussions
    url: https://github.com/wallix/terraform-provider-wallix-bastion/discussions
    about: Ask questions and discuss with the community
