# This GitHub action can publish assets for release when a tag is created.
# Currently its setup to run on any tag that matches the pattern "v*" (ie. v0.1.0).
name: release
on:
  push:
    tags:
      - v*
permissions:
  contents: write  # Changed from 'read' to 'write' for release creation
  packages: write
  issues: read
  pull-requests: read
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Full history needed for changelog generation

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'  # Use Go version from go.mod instead of hardcoded
          cache: true  # Enable Go module caching

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6.3.0
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6.4.0
        with:
          version: v2.12.0  # Lock to specific version instead of 'latest'
          args: release --clean
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
