---
name: Security Scanning

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 6 * * 1'  # Weekly on Monday at 6 AM UTC

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  # Static security analysis
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    strategy:
      fail-fast: false
      matrix:
        language: [go]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
          cache-dependency-path: |
            go.sum
            go.mod
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: security-and-quality
          # Disable default cache to avoid conflicts
          setup-python-dependencies: false
      
      - name: Build
        run: go build -v ./...
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          # Use unique category to avoid cache conflicts
          category: "/language:${{matrix.language}}"
  
  # Dependency vulnerabilities
  dependency-scan:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      
      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-file: go.mod
          check-latest: false
      
      - name: Run OSV Scanner (dependency vulnerability scanner)
        uses: google/osv-scanner-action@v1.8.5
        with:
          scan-args: |-
            --recursive
            --skip-git
            --format=sarif
            --output=osv-results.sarif
            ./
        continue-on-error: true  # Don't fail the job on vulnerabilities, just report them
      
      - name: Upload OSV scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'osv-results.sarif'
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.27.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-fs-results.sarif'
          severity: 'CRITICAL,HIGH'
        continue-on-error: true  # Don't fail the job on vulnerabilities, just report them
      
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-fs-results.sarif'
  
  # Secret scanning
  secret-scan:
    name: Secret Scan
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      
      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@v3.84.2
        with:
          path: ./
          base: ""
          head: ""
          extra_args: --only-verified --no-update
        continue-on-error: true  # Don't fail on secrets found, just report them
  
  # Container security (if using Docker)
  container-scan:
    name: Container Security Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Build test container
        run: |
          cat > Dockerfile.test << 'EOF'
          FROM golang:1.23-alpine AS builder
          WORKDIR /app
          COPY go.mod go.sum ./
          RUN go mod download
          COPY . .
          RUN CGO_ENABLED=0 go build -o terraform-provider-wallix-bastion
          
          FROM alpine:latest
          RUN apk --no-cache add ca-certificates
          WORKDIR /root/
          COPY --from=builder /app/terraform-provider-wallix-bastion .
          CMD ["./terraform-provider-wallix-bastion"]
          EOF
          
          docker build -f Dockerfile.test -t wallix-bastion-provider:test .
        continue-on-error: false
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.27.0
        with:
          image-ref: 'wallix-bastion-provider:test'
          format: 'sarif'
          output: 'trivy-container-results.sarif'
          severity: 'CRITICAL,HIGH'
        continue-on-error: true
      
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-container-results.sarif'
